### ISSUE TITLE
box86 segfault while loading eggnogg

### ISSUE THREAD

**Issue by Thaeron** [ptitSeb/box86#243]
I try to play eggnogg classic (which is 32 bits binary) from https://madgarden.itch.io/eggnogg through box86 on RPi4 but I get segmentation fault.
The strange thing is that box86 seems to not find Mix_RegisterEffect from libSDL_mixer while other functions from the lib are properly found.
```
PltReolver: Apply Global R_386_JMP_SLOT @0x807f090 with sym=Mix_OpenAudio (0x80495f6 -> 0x6406a4eb / (noelf))
 return 0x00000000
1824|0x805ef4e: Calling Mix_OpenAudio (00005622, 00008010, 00000002...) => return 0x00000000
 ...  =>PltResolver: Addr=0x640331d0, Slot=688 Return=0x8050f6b: elf is ./eggnogg
PltReolver: Apply Global R_386_JMP_SLOT @0x807f158 with sym=memset (0x8049916 -> 0x6406ef2d / (noelf))
 return 0x00000000
1824|0x8050f6b: Calling memset (081372E0, 00000000, 0000602C...) => return 0x081372E0
1824|0x805df58: Calling SDL_GetTicks (00000000, 00000000, 00000000...) => return 0x000001B6
1824|0x8050fdb: Calling __printf_chk (00000001, 080720E8, D2F1AA00...) =>[mad 0.00s (26)]  return 0x00000011
1824|0x805ef84: Calling __printf_chk (00000001, 080726E5, 080726DC...) =>syn_init sample rate 22050
 return 0x0000001B
 ...  =>PltResolver: Addr=0x640331d0, Slot=248 Return=0x805efa8: elf is ./eggnogg
Error: PltReolver: Symbol Mix_RegisterEffect not found, cannot apply R_386_JMP_SLOT @0x807f07c (0x80495a6) in ./eggnogg
 return 0x0000001B
 return 0x00000000
Emulation finished, EAX=0
Calling atexit registered functions
Calling atexit registered functions
Calling fini for all loaded elfs
Calling Fini for ./eggnogg @0x80720bc
```
backtrace with GDB 
```
 ...  =>PltResolver: Addr=0x62bdc5f8, Slot=248 Return=0x805efa8: elf is ./eggnogg
Error: PltReolver: Symbol Mix_RegisterEffect not found, cannot apply R_386_JMP_SLOT @0x807f07c (0x80495a6) in ./eggnogg
 return 0x0000001B
 return 0x00000000
Emulation finished, EAX=0
Calling atexit registered functions
Calling atexit registered functions
Calling fini for all loaded elfs
Calling Fini for ./eggnogg @0x80720bc

Thread 3 "box86" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb38892f0 (LWP 1860)]
0xb610fcec in SDL_Delay () from /usr/lib/arm-linux-gnueabihf/libSDL-1.2.so.0
(gdb) where
#0  0xb610fcec in SDL_Delay () from /usr/lib/arm-linux-gnueabihf/libSDL-1.2.so.0
#1  0xb6ee0b44 in __GI___nanosleep (remaining=<optimized out>, requested_time=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#2  __GI___nanosleep (requested_time=0x0, remaining=<optimized out>) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#3  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```
[eggnogg.log](https://github.com/ptitSeb/box86/files/5471528/eggnogg.log)
[gdb.log](https://github.com/ptitSeb/box86/files/5471529/gdb.log)

**Comment by ptitSeb** [comment]
Yeah, that was one of the few function still not wrapped in sdl1_mixer. It's done now. Game seems to work fine.

**Comment by ptitSeb** [comment]
Also, while the "plus" linux version doesn't work because it's 64bits, the "plus" windows version works with wine

**Comment by Thaeron** [comment]
I confirm it works great now. Thank you for the fix !
