### ISSUE TITLE
La-Maluna: fails to boot, missing symbols.

### ISSUE THREAD

**Issue by ITotalJustice** [ptitSeb/box86#38]
The output when trying to run the game.
```
BOX86_LD_LIBRARY_PATH=.:lib:lib/lib:x86:lib32:/usr/i686-linux-gnu/lib:/usr/lib/arm-linux-gnueabihf box86 LaMulana.bin.x86 
BOX86_LD_LIBRARY_PATH: ./:lib/:lib/lib/:x86/:lib32/:/usr/i686-linux-gnu/lib/:/usr/lib/arm-linux-gnueabihf/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for LaMulana.bin.x86
Using native(wrapped) libpthread.so.0
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libopenal.so.1
Using native(wrapped) libGL.so.1
Using emulated /usr/i686-linux-gnu/lib/libstdc++.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using emulated /usr/i686-linux-gnu/lib/libgcc_s.so.1
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT @0xb5d42198 (0x6b676)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_386_JMP_SLOT @0xb5d42474 (0x6c1e6)
Error: Symbol wprintf not found, cannot apply R_386_JMP_SLOT @0x8448e6c (0x80c130e)
Error: Symbol SDL_wcslen not found, cannot apply R_386_JMP_SLOT @0x8448f78 (0x80c173e)
Segmentation fault
```
and the bt
```
#0  0xa8056f6c in myStackAlign (fmt=fmt@entry=0x400 <error: Cannot access memory at address 0x400>, st=0x83d89dc, mystack=0xa80cbf08) at /home/pi/box86/src/libtools/myalign.c:20
#1  0xa8065a3c in my2_SDL_snprintf (emu=emu@entry=0xa80cbb10, buff=0xb6c84e90, fmt=0x400, b=<optimized out>, V=...) at /home/pi/box86/src/wrapped/wrappedsdl2.c:605
#2  0xa801d118 in iFEpupVV (emu=emu@entry=0xa80cbb10, fcn=fcn@entry=2818988572) at /home/pi/box86/src/wrapped/generated/wrapper.c:1518
#3  0xa8055058 in x86Int3 (emu=0xa80cbb10) at /home/pi/box86/src/emu/x86int3.c:186
#4  0xa8037134 in Run (emu=0xa80cbb10) at /home/pi/box86/src/emu/x86run.c:865
#5  0xa8006bd4 in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /home/pi/box86/src/main.c:425
```

**Comment by ptitSeb** [comment]
Thanks for the log.

I have fixed SDL_snprintf and added the 2 missing functions. It should go farther now.

**Comment by ITotalJustice** [comment]
Perfect, game now boots and runs!

Not fullspeed sadly, very sluggish, But its another game to add to the working list! Closing.

**Comment by ptitSeb** [comment]
Good it works !

The sluggish effect is probably du to the fact the game doesn't use OpenGL, but is pure software blit. Because all OpenGL and high level function are run native, the most the game is "modern" and use hardware, the faster it will be (same for Rampage City).

**Comment by ITotalJustice** [comment]
Ah that makes sense, thanks for explaining.
