### ISSUE TITLE
Help with a Python library

### ISSUE THREAD

**Issue by retropiepro** [ptitSeb/box86#383]
Hello!

Again, I want to thank you for this amazing project!

I'm wondering if you can help me figure out if I can use a specific x86 python [library](https://pypi.org/project/cos-aspera/) on RPI4.

Currently, when I run it I get an Import Error with the following message **wrong ELF class: ELFCLASS64**

Full log snippet
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cos_aspera/faspmanager2.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.6/site-packages/cos_aspera/_faspmanager2.so: wrong ELF class: ELFCLASS64`

Any idea will help.
Thanks!

**Comment by ptitSeb** [comment]
Sorry, but that's because that lib is a 64bits version, and box86 only do 32bits.

**Comment by retropiepro** [comment]
Thanks!
