### ISSUE TITLE
Attempt to run x86 java failed

### ISSUE THREAD

**Issue by CPXMC** [ptitSeb/box86#416]
This is the console output

./java
Box86 with Dynarec v0.2.3 4710c477 built on Jul  3 2021 20:58:19
Error: Global Symbol collector_func_load version 0/(none) not found, cannot apply R_386_GLOB_DAT 0x7568dff8 ((nil)) in /home/pi/jre1.8.0_291/lib/i386/client/libjvm.so
Java HotSpot(TM) Client VM warning: Can't detect primordial thread stack location - find_vma failed
Error: PltReolver: Symbol VerifyFixClassname(ver 6: VerifyFixClassname@SUNWprivate_1.1) not found, cannot apply R_386_JMP_SLOT 0x73ff7114 (0x73fd85f6) in /home/pi/jre1.8.0_291/lib/i386/libjava.so

**Comment by ptitSeb** [comment]
I know, java is not supported for now.

**Comment by Painadath** [comment]
@CPXMC why could u do that java is in armhf

**Comment by leonpano2006** [comment]
Why you need to run Java in x86-64?
Same Java app should work on aarch64 or armhf without issue ex. Minecraft(with mods/without mods)

**Comment by Painadath** [comment]
Yes

**Comment by azubieta** [comment]
I'm trying to run an app that's is made using Java but depends on several dlls' therefore I need to use wine + box86 to run it. But I'm getting the following error:

```
Error occurred during initialization of VM
java.lang.ClassCastException: <unknown> cannot be cast to [Ljava.lang.Class;
        at java.lang.reflect.Constructor.getParameterTypes(Unknown Source)
        at java.lang.Class.getConstructor0(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at sun.nio.cs.FastCharsetProvider.lookup(Unknown Source)
        at sun.nio.cs.FastCharsetProvider.charsetForName(Unknown Source)
        at java.nio.charset.Charset.lookup2(Unknown Source)
        at java.nio.charset.Charset.lookup(Unknown Source)
        at java.nio.charset.Charset.forName(Unknown Source)
        at java.io.PrintStream.toCharset(Unknown Source)
        at java.io.PrintStream.<init>(Unknown Source)
        at java.lang.System.newPrintStream(Unknown Source)
        at java.lang.System.initializeSystemClass(Unknown Source)
```

Any ideas of what could be wrong ?
