### ISSUE TITLE
The Witcher 2: Fails to boot, Missing sdl symbols.

### ISSUE THREAD

**Issue by ITotalJustice** [ptitSeb/box86#43]
Theres quite a few missing symbols, a few of them being sdl.
```
Error: Symbol alcCreateContext not found, cannot apply R_386_32 @0xb5b73e84 ((nil))
Error: Symbol alcMakeContextCurrent not found, cannot apply R_386_32 @0xb5b73e8c ((nil))
Error: Symbol alcProcessContext not found, cannot apply R_386_32 @0xb5b73e94 ((nil))
Error: Symbol alcSuspendContext not found, cannot apply R_386_32 @0xb5b73e9c ((nil))
Error: Symbol alcDestroyContext not found, cannot apply R_386_32 @0xb5b73ea4 ((nil))
Error: Symbol alcGetCurrentContext not found, cannot apply R_386_32 @0xb5b73eac ((nil))
Error: Symbol alcGetContextsDevice not found, cannot apply R_386_32 @0xb5b73eb4 ((nil))
Error: Symbol alcOpenDevice not found, cannot apply R_386_32 @0xb5b73ebc ((nil))
Error: Symbol alcCloseDevice not found, cannot apply R_386_32 @0xb5b73ec4 ((nil))
Error: Symbol alcGetError not found, cannot apply R_386_32 @0xb5b73ecc ((nil))
Error: Symbol alcIsExtensionPresent not found, cannot apply R_386_32 @0xb5b73ed4 ((nil))
Error: Symbol alcGetProcAddress not found, cannot apply R_386_32 @0xb5b73edc ((nil))
Error: Symbol alcGetEnumValue not found, cannot apply R_386_32 @0xb5b73ee4 ((nil))
Error: Symbol alcGetString not found, cannot apply R_386_32 @0xb5b73eec ((nil))
Error: Symbol alcGetIntegerv not found, cannot apply R_386_32 @0xb5b73ef4 ((nil))
Error: Symbol alcCaptureOpenDevice not found, cannot apply R_386_32 @0xb5b73efc ((nil))
Error: Symbol alcCaptureCloseDevice not found, cannot apply R_386_32 @0xb5b73f04 ((nil))
Error: Symbol alcCaptureStart not found, cannot apply R_386_32 @0xb5b73f0c ((nil))
Error: Symbol alcCaptureStop not found, cannot apply R_386_32 @0xb5b73f14 ((nil))
Error: Symbol alcCaptureSamples not found, cannot apply R_386_32 @0xb5b73f1c ((nil))
Error: Symbol alcSetThreadContext not found, cannot apply R_386_32 @0xb5b73f24 ((nil))
Error: Symbol alcGetThreadContext not found, cannot apply R_386_32 @0xb5b73f2c ((nil))
Error: Symbol alcLoopbackOpenDeviceSOFT not found, cannot apply R_386_32 @0xb5b73f34 ((nil))
Error: Symbol alcIsRenderFormatSupportedSOFT not found, cannot apply R_386_32 @0xb5b73f3c ((nil))
Error: Symbol alcRenderSamplesSOFT not found, cannot apply R_386_32 @0xb5b73f44 ((nil))
Error: Symbol alcDevicePauseSOFT not found, cannot apply R_386_32 @0xb5b73f4c ((nil))
Error: Symbol alcDeviceResumeSOFT not found, cannot apply R_386_32 @0xb5b73f54 ((nil))
Error: Symbol alcGetInteger64vSOFT not found, cannot apply R_386_32 @0xb5b73f5c ((nil))
Error: Symbol alEnable not found, cannot apply R_386_32 @0xb5b73f64 ((nil))
Error: Symbol alDisable not found, cannot apply R_386_32 @0xb5b73f6c ((nil))
Error: Symbol alIsEnabled not found, cannot apply R_386_32 @0xb5b73f74 ((nil))
Error: Symbol alGetString not found, cannot apply R_386_32 @0xb5b73f7c ((nil))
Error: Symbol alGetBooleanv not found, cannot apply R_386_32 @0xb5b73f84 ((nil))
Error: Symbol alGetIntegerv not found, cannot apply R_386_32 @0xb5b73f8c ((nil))
Error: Symbol alGetFloatv not found, cannot apply R_386_32 @0xb5b73f94 ((nil))
Error: Symbol alGetDoublev not found, cannot apply R_386_32 @0xb5b73f9c ((nil))
Error: Symbol alGetBoolean not found, cannot apply R_386_32 @0xb5b73fa4 ((nil))
Error: Symbol alGetInteger not found, cannot apply R_386_32 @0xb5b73fac ((nil))
Error: Symbol alGetFloat not found, cannot apply R_386_32 @0xb5b73fb4 ((nil))
Error: Symbol alGetDouble not found, cannot apply R_386_32 @0xb5b73fbc ((nil))
Error: Symbol alGetError not found, cannot apply R_386_32 @0xb5b73fc4 ((nil))
Error: Symbol alIsExtensionPresent not found, cannot apply R_386_32 @0xb5b73fcc ((nil))
Error: Symbol alGetProcAddress not found, cannot apply R_386_32 @0xb5b73fd4 ((nil))
Error: Symbol alGetEnumValue not found, cannot apply R_386_32 @0xb5b73fdc ((nil))
Error: Symbol alListenerf not found, cannot apply R_386_32 @0xb5b73fe4 ((nil))
Error: Symbol alListener3f not found, cannot apply R_386_32 @0xb5b73fec ((nil))
Error: Symbol alListenerfv not found, cannot apply R_386_32 @0xb5b73ff4 ((nil))
Error: Symbol alListeneri not found, cannot apply R_386_32 @0xb5b73ffc ((nil))
Error: Symbol alListener3i not found, cannot apply R_386_32 @0xb5b74004 ((nil))
Error: Symbol alListeneriv not found, cannot apply R_386_32 @0xb5b7400c ((nil))
Error: Symbol alGetListenerf not found, cannot apply R_386_32 @0xb5b74014 ((nil))
Error: Symbol alGetListener3f not found, cannot apply R_386_32 @0xb5b7401c ((nil))
Error: Symbol alGetListenerfv not found, cannot apply R_386_32 @0xb5b74024 ((nil))
Error: Symbol alGetListeneri not found, cannot apply R_386_32 @0xb5b7402c ((nil))
Error: Symbol alGetListener3i not found, cannot apply R_386_32 @0xb5b74034 ((nil))
Error: Symbol alGetListeneriv not found, cannot apply R_386_32 @0xb5b7403c ((nil))
Error: Symbol alGenSources not found, cannot apply R_386_32 @0xb5b74044 ((nil))
Error: Symbol alDeleteSources not found, cannot apply R_386_32 @0xb5b7404c ((nil))
Error: Symbol alIsSource not found, cannot apply R_386_32 @0xb5b74054 ((nil))
Error: Symbol alSourcef not found, cannot apply R_386_32 @0xb5b7405c ((nil))
Error: Symbol alSource3f not found, cannot apply R_386_32 @0xb5b74064 ((nil))
Error: Symbol alSourcefv not found, cannot apply R_386_32 @0xb5b7406c ((nil))
Error: Symbol alSourcei not found, cannot apply R_386_32 @0xb5b74074 ((nil))
Error: Symbol alSource3i not found, cannot apply R_386_32 @0xb5b7407c ((nil))
Error: Symbol alSourceiv not found, cannot apply R_386_32 @0xb5b74084 ((nil))
Error: Symbol alGetSourcef not found, cannot apply R_386_32 @0xb5b7408c ((nil))
Error: Symbol alGetSource3f not found, cannot apply R_386_32 @0xb5b74094 ((nil))
Error: Symbol alGetSourcefv not found, cannot apply R_386_32 @0xb5b7409c ((nil))
Error: Symbol alGetSourcei not found, cannot apply R_386_32 @0xb5b740a4 ((nil))
Error: Symbol alGetSource3i not found, cannot apply R_386_32 @0xb5b740ac ((nil))
Error: Symbol alGetSourceiv not found, cannot apply R_386_32 @0xb5b740b4 ((nil))
Error: Symbol alSourcePlayv not found, cannot apply R_386_32 @0xb5b740bc ((nil))
Error: Symbol alSourceStopv not found, cannot apply R_386_32 @0xb5b740c4 ((nil))
Error: Symbol alSourceRewindv not found, cannot apply R_386_32 @0xb5b740cc ((nil))
Error: Symbol alSourcePausev not found, cannot apply R_386_32 @0xb5b740d4 ((nil))
Error: Symbol alSourcePlay not found, cannot apply R_386_32 @0xb5b740dc ((nil))
Error: Symbol alSourceStop not found, cannot apply R_386_32 @0xb5b740e4 ((nil))
Error: Symbol alSourceRewind not found, cannot apply R_386_32 @0xb5b740ec ((nil))
Error: Symbol alSourcePause not found, cannot apply R_386_32 @0xb5b740f4 ((nil))
Error: Symbol alSourceQueueBuffers not found, cannot apply R_386_32 @0xb5b740fc ((nil))
Error: Symbol alSourceUnqueueBuffers not found, cannot apply R_386_32 @0xb5b74104 ((nil))
Error: Symbol alGenBuffers not found, cannot apply R_386_32 @0xb5b7410c ((nil))
Error: Symbol alDeleteBuffers not found, cannot apply R_386_32 @0xb5b74114 ((nil))
Error: Symbol alIsBuffer not found, cannot apply R_386_32 @0xb5b7411c ((nil))
Error: Symbol alBufferData not found, cannot apply R_386_32 @0xb5b74124 ((nil))
Error: Symbol alBufferf not found, cannot apply R_386_32 @0xb5b7412c ((nil))
Error: Symbol alBuffer3f not found, cannot apply R_386_32 @0xb5b74134 ((nil))
Error: Symbol alBufferfv not found, cannot apply R_386_32 @0xb5b7413c ((nil))
Error: Symbol alBufferi not found, cannot apply R_386_32 @0xb5b74144 ((nil))
Error: Symbol alBuffer3i not found, cannot apply R_386_32 @0xb5b7414c ((nil))
Error: Symbol alBufferiv not found, cannot apply R_386_32 @0xb5b74154 ((nil))
Error: Symbol alGetBufferf not found, cannot apply R_386_32 @0xb5b7415c ((nil))
Error: Symbol alGetBuffer3f not found, cannot apply R_386_32 @0xb5b74164 ((nil))
Error: Symbol alGetBufferfv not found, cannot apply R_386_32 @0xb5b7416c ((nil))
Error: Symbol alGetBufferi not found, cannot apply R_386_32 @0xb5b74174 ((nil))
Error: Symbol alGetBuffer3i not found, cannot apply R_386_32 @0xb5b7417c ((nil))
Error: Symbol alGetBufferiv not found, cannot apply R_386_32 @0xb5b74184 ((nil))
Error: Symbol alDopplerFactor not found, cannot apply R_386_32 @0xb5b7418c ((nil))
Error: Symbol alDopplerVelocity not found, cannot apply R_386_32 @0xb5b74194 ((nil))
Error: Symbol alSpeedOfSound not found, cannot apply R_386_32 @0xb5b7419c ((nil))
Error: Symbol alDistanceModel not found, cannot apply R_386_32 @0xb5b741a4 ((nil))
Error: Symbol alGenFilters not found, cannot apply R_386_32 @0xb5b741ac ((nil))
Error: Symbol alDeleteFilters not found, cannot apply R_386_32 @0xb5b741b4 ((nil))
Error: Symbol alIsFilter not found, cannot apply R_386_32 @0xb5b741bc ((nil))
Error: Symbol alFilteri not found, cannot apply R_386_32 @0xb5b741c4 ((nil))
Error: Symbol alFilteriv not found, cannot apply R_386_32 @0xb5b741cc ((nil))
Error: Symbol alFilterf not found, cannot apply R_386_32 @0xb5b741d4 ((nil))
Error: Symbol alFilterfv not found, cannot apply R_386_32 @0xb5b741dc ((nil))
Error: Symbol alGetFilteri not found, cannot apply R_386_32 @0xb5b741e4 ((nil))
Error: Symbol alGetFilteriv not found, cannot apply R_386_32 @0xb5b741ec ((nil))
Error: Symbol alGetFilterf not found, cannot apply R_386_32 @0xb5b741f4 ((nil))
Error: Symbol alGetFilterfv not found, cannot apply R_386_32 @0xb5b741fc ((nil))
Error: Symbol alGenEffects not found, cannot apply R_386_32 @0xb5b74204 ((nil))
Error: Symbol alDeleteEffects not found, cannot apply R_386_32 @0xb5b7420c ((nil))
Error: Symbol alIsEffect not found, cannot apply R_386_32 @0xb5b74214 ((nil))
Error: Symbol alEffecti not found, cannot apply R_386_32 @0xb5b7421c ((nil))
Error: Symbol alEffectiv not found, cannot apply R_386_32 @0xb5b74224 ((nil))
Error: Symbol alEffectf not found, cannot apply R_386_32 @0xb5b7422c ((nil))
Error: Symbol alEffectfv not found, cannot apply R_386_32 @0xb5b74234 ((nil))
Error: Symbol alGetEffecti not found, cannot apply R_386_32 @0xb5b7423c ((nil))
Error: Symbol alGetEffectiv not found, cannot apply R_386_32 @0xb5b74244 ((nil))
Error: Symbol alGetEffectf not found, cannot apply R_386_32 @0xb5b7424c ((nil))
Error: Symbol alGetEffectfv not found, cannot apply R_386_32 @0xb5b74254 ((nil))
Error: Symbol alGenAuxiliaryEffectSlots not found, cannot apply R_386_32 @0xb5b7425c ((nil))
Error: Symbol alDeleteAuxiliaryEffectSlots not found, cannot apply R_386_32 @0xb5b74264 ((nil))
Error: Symbol alIsAuxiliaryEffectSlot not found, cannot apply R_386_32 @0xb5b7426c ((nil))
Error: Symbol alAuxiliaryEffectSloti not found, cannot apply R_386_32 @0xb5b74274 ((nil))
Error: Symbol alAuxiliaryEffectSlotiv not found, cannot apply R_386_32 @0xb5b7427c ((nil))
Error: Symbol alAuxiliaryEffectSlotf not found, cannot apply R_386_32 @0xb5b74284 ((nil))
Error: Symbol alAuxiliaryEffectSlotfv not found, cannot apply R_386_32 @0xb5b7428c ((nil))
Error: Symbol alGetAuxiliaryEffectSloti not found, cannot apply R_386_32 @0xb5b74294 ((nil))
Error: Symbol alGetAuxiliaryEffectSlotiv not found, cannot apply R_386_32 @0xb5b7429c ((nil))
Error: Symbol alGetAuxiliaryEffectSlotf not found, cannot apply R_386_32 @0xb5b742a4 ((nil))
Error: Symbol alGetAuxiliaryEffectSlotfv not found, cannot apply R_386_32 @0xb5b742ac ((nil))
Error: Symbol alBufferSubDataSOFT not found, cannot apply R_386_32 @0xb5b742b4 ((nil))
Error: Symbol alBufferSamplesSOFT not found, cannot apply R_386_32 @0xb5b742bc ((nil))
Error: Symbol alBufferSubSamplesSOFT not found, cannot apply R_386_32 @0xb5b742c4 ((nil))
Error: Symbol alGetBufferSamplesSOFT not found, cannot apply R_386_32 @0xb5b742cc ((nil))
Error: Symbol alIsBufferFormatSupportedSOFT not found, cannot apply R_386_32 @0xb5b742d4 ((nil))
Error: Symbol alDeferUpdatesSOFT not found, cannot apply R_386_32 @0xb5b742dc ((nil))
Error: Symbol alProcessUpdatesSOFT not found, cannot apply R_386_32 @0xb5b742e4 ((nil))
Error: Symbol alSourcedSOFT not found, cannot apply R_386_32 @0xb5b742ec ((nil))
Error: Symbol alSource3dSOFT not found, cannot apply R_386_32 @0xb5b742f4 ((nil))
Error: Symbol alSourcedvSOFT not found, cannot apply R_386_32 @0xb5b742fc ((nil))
Error: Symbol alGetSourcedSOFT not found, cannot apply R_386_32 @0xb5b74304 ((nil))
Error: Symbol alGetSource3dSOFT not found, cannot apply R_386_32 @0xb5b7430c ((nil))
Error: Symbol alGetSourcedvSOFT not found, cannot apply R_386_32 @0xb5b74314 ((nil))
Error: Symbol alSourcei64SOFT not found, cannot apply R_386_32 @0xb5b7431c ((nil))
Error: Symbol alSource3i64SOFT not found, cannot apply R_386_32 @0xb5b74324 ((nil))
Error: Symbol alSourcei64vSOFT not found, cannot apply R_386_32 @0xb5b7432c ((nil))
Error: Symbol alGetSourcei64SOFT not found, cannot apply R_386_32 @0xb5b74334 ((nil))
Error: Symbol alGetSource3i64SOFT not found, cannot apply R_386_32 @0xb5b7433c ((nil))
Error: Symbol alGetSourcei64vSOFT not found, cannot apply R_386_32 @0xb5b74344 ((nil))
Error: Symbol alGenSoundfontsSOFT not found, cannot apply R_386_32 @0xb5b7434c ((nil))
Error: Symbol alDeleteSoundfontsSOFT not found, cannot apply R_386_32 @0xb5b74354 ((nil))
Error: Symbol alIsSoundfontSOFT not found, cannot apply R_386_32 @0xb5b7435c ((nil))
Error: Symbol alGetSoundfontivSOFT not found, cannot apply R_386_32 @0xb5b74364 ((nil))
Error: Symbol alSoundfontPresetsSOFT not found, cannot apply R_386_32 @0xb5b7436c ((nil))
Error: Symbol alGenPresetsSOFT not found, cannot apply R_386_32 @0xb5b74374 ((nil))
Error: Symbol alDeletePresetsSOFT not found, cannot apply R_386_32 @0xb5b7437c ((nil))
Error: Symbol alIsPresetSOFT not found, cannot apply R_386_32 @0xb5b74384 ((nil))
Error: Symbol alPresetiSOFT not found, cannot apply R_386_32 @0xb5b7438c ((nil))
Error: Symbol alPresetivSOFT not found, cannot apply R_386_32 @0xb5b74394 ((nil))
Error: Symbol alGetPresetivSOFT not found, cannot apply R_386_32 @0xb5b7439c ((nil))
Error: Symbol alPresetFontsoundsSOFT not found, cannot apply R_386_32 @0xb5b743a4 ((nil))
Error: Symbol alGenFontsoundsSOFT not found, cannot apply R_386_32 @0xb5b743ac ((nil))
Error: Symbol alDeleteFontsoundsSOFT not found, cannot apply R_386_32 @0xb5b743b4 ((nil))
Error: Symbol alIsFontsoundSOFT not found, cannot apply R_386_32 @0xb5b743bc ((nil))
Error: Symbol alFontsoundiSOFT not found, cannot apply R_386_32 @0xb5b743c4 ((nil))
Error: Symbol alFontsound2iSOFT not found, cannot apply R_386_32 @0xb5b743cc ((nil))
Error: Symbol alFontsoundivSOFT not found, cannot apply R_386_32 @0xb5b743d4 ((nil))
Error: Symbol alGetFontsoundivSOFT not found, cannot apply R_386_32 @0xb5b743dc ((nil))
Error: Symbol alFontsoundModulatoriSOFT not found, cannot apply R_386_32 @0xb5b743e4 ((nil))
Error: Symbol alGetFontsoundModulatorivSOFT not found, cannot apply R_386_32 @0xb5b743ec ((nil))
Error: Symbol alMidiSoundfontSOFT not found, cannot apply R_386_32 @0xb5b743f4 ((nil))
Error: Symbol alMidiSoundfontvSOFT not found, cannot apply R_386_32 @0xb5b743fc ((nil))
Error: Symbol alMidiEventSOFT not found, cannot apply R_386_32 @0xb5b74404 ((nil))
Error: Symbol alMidiSysExSOFT not found, cannot apply R_386_32 @0xb5b7440c ((nil))
Error: Symbol alMidiPlaySOFT not found, cannot apply R_386_32 @0xb5b74414 ((nil))
Error: Symbol alMidiPauseSOFT not found, cannot apply R_386_32 @0xb5b7441c ((nil))
Error: Symbol alMidiStopSOFT not found, cannot apply R_386_32 @0xb5b74424 ((nil))
Error: Symbol alMidiResetSOFT not found, cannot apply R_386_32 @0xb5b7442c ((nil))
Error: Symbol alMidiGainSOFT not found, cannot apply R_386_32 @0xb5b74434 ((nil))
Error: Symbol alGetInteger64SOFT not found, cannot apply R_386_32 @0xb5b7443c ((nil))
Error: Symbol alGetInteger64vSOFT not found, cannot apply R_386_32 @0xb5b74444 ((nil))
Error: Symbol alLoadSoundfontSOFT not found, cannot apply R_386_32 @0xb5b7444c ((nil))
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT @0xb5ac8198 (0x6b676)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_386_JMP_SLOT @0xb5ac8474 (0x6c1e6)
Error: Symbol alDeleteBuffers not found, cannot apply R_386_JMP_SLOT @0x203732a8 (0x20007066)
Error: Symbol alcMakeContextCurrent not found, cannot apply R_386_JMP_SLOT @0x203732ac (0x20007076)
Error: Symbol alGenSources not found, cannot apply R_386_JMP_SLOT @0x203732d8 (0x20007126)
Error: Symbol alDistanceModel not found, cannot apply R_386_JMP_SLOT @0x2037331c (0x20007236)
Error: Symbol alcCaptureCloseDevice not found, cannot apply R_386_JMP_SLOT @0x20373334 (0x20007296)
Error: Symbol alSourceRewind not found, cannot apply R_386_JMP_SLOT @0x20373368 (0x20007366)
Error: Symbol alSourceQueueBuffers not found, cannot apply R_386_JMP_SLOT @0x20373398 (0x20007426)
Error: Symbol alProcessUpdatesSOFT not found, cannot apply R_386_JMP_SLOT @0x203733e8 (0x20007566)
Error: Symbol SDL_PeepEvents not found, cannot apply R_386_JMP_SLOT @0x20373420 (0x20007646)
Error: Symbol alcCaptureStart not found, cannot apply R_386_JMP_SLOT @0x20373428 (0x20007666)
Error: Symbol alDeferUpdatesSOFT not found, cannot apply R_386_JMP_SLOT @0x20373444 (0x200076d6)
Error: Symbol alcOpenDevice not found, cannot apply R_386_JMP_SLOT @0x20373478 (0x200077a6)
Error: Symbol alcCaptureSamples not found, cannot apply R_386_JMP_SLOT @0x20373488 (0x200077e6)
Error: Symbol tempnam not found, cannot apply R_386_JMP_SLOT @0x203734a4 (0x20007856)
Error: Symbol alSourcei not found, cannot apply R_386_JMP_SLOT @0x203734dc (0x20007936)
Error: Symbol SDL_SetWindowMaximumSize not found, cannot apply R_386_JMP_SLOT @0x20373514 (0x20007a16)
Error: Symbol SDL_GetWindowMaximumSize not found, cannot apply R_386_JMP_SLOT @0x2037352c (0x20007a76)
Error: Symbol alDopplerFactor not found, cannot apply R_386_JMP_SLOT @0x20373548 (0x20007ae6)
Error: Symbol alGetSourcei not found, cannot apply R_386_JMP_SLOT @0x20373558 (0x20007b26)
Error: Symbol SDL_GetWindowFromID not found, cannot apply R_386_JMP_SLOT @0x203735ac (0x20007c76)
Error: Symbol alDeleteSources not found, cannot apply R_386_JMP_SLOT @0x203735e0 (0x20007d46)
Error: Symbol alSource3f not found, cannot apply R_386_JMP_SLOT @0x203735f0 (0x20007d86)
Error: Symbol alSourceUnqueueBuffers not found, cannot apply R_386_JMP_SLOT @0x20373630 (0x20007e86)
Error: Symbol alcDestroyContext not found, cannot apply R_386_JMP_SLOT @0x20373650 (0x20007f06)
Error: Symbol alSourcePlay not found, cannot apply R_386_JMP_SLOT @0x20373678 (0x20007fa6)
Error: Symbol alListenerfv not found, cannot apply R_386_JMP_SLOT @0x2037368c (0x20007ff6)
Error: Symbol alcCaptureStop not found, cannot apply R_386_JMP_SLOT @0x203736c4 (0x200080d6)
Error: Symbol alcGetIntegerv not found, cannot apply R_386_JMP_SLOT @0x203736cc (0x200080f6)
Error: Symbol SDL_GetWindowGammaRamp not found, cannot apply R_386_JMP_SLOT @0x203736f0 (0x20008186)
Error: Symbol alcCreateContext not found, cannot apply R_386_JMP_SLOT @0x20373704 (0x200081d6)
Error: Symbol alBufferData not found, cannot apply R_386_JMP_SLOT @0x2037370c (0x200081f6)
Error: Symbol alGenBuffers not found, cannot apply R_386_JMP_SLOT @0x2037374c (0x200082f6)
Error: Symbol alSourcef not found, cannot apply R_386_JMP_SLOT @0x203737bc (0x200084b6)
Error: Symbol alcCloseDevice not found, cannot apply R_386_JMP_SLOT @0x20373860 (0x20008746)
Error: Symbol alcCaptureOpenDevice not found, cannot apply R_386_JMP_SLOT @0x20373870 (0x20008786)
Error: Symbol SDL_SetWindowData not found, cannot apply R_386_JMP_SLOT @0x203738b4 (0x20008896)
Error: Symbol alBufferSubDataSOFT not found, cannot apply R_386_JMP_SLOT @0x203738d0 (0x20008906)
Error: Symbol SDL_SetWindowGammaRamp not found, cannot apply R_386_JMP_SLOT @0x203738f0 (0x20008986)
Error: Symbol SDL_GetMouseFocus not found, cannot apply R_386_JMP_SLOT @0x2037390c (0x200089f6)
Error: Symbol alGetSourceiv not found, cannot apply R_386_JMP_SLOT @0x20373924 (0x20008a56)
Error: Symbol SDL_GetWindowData not found, cannot apply R_386_JMP_SLOT @0x20373990 (0x20008c06)
Error: Symbol alSourcefv not found, cannot apply R_386_JMP_SLOT @0x20373a2c (0x20008e76)
Error: Symbol SDL_GetDefaultCursor not found, cannot apply R_386_JMP_SLOT @0x20373a38 (0x20008ea6)
Error: Symbol alSourcePause not found, cannot apply R_386_JMP_SLOT @0x20373a5c (0x20008f36)
Error: Symbol alSourceStop not found, cannot apply R_386_JMP_SLOT @0x20373a6c (0x20008f76)
Error: Symbol alListenerf not found, cannot apply R_386_JMP_SLOT @0x20373a7c (0x20008fb6)
PltResolver: Ofs=0x20016cb2, Id=1032 (IP=(nil))
```
I don't expect this game to run at a fps higher than 1, but thought it would be impressive to have it working regardless ;)

**Comment by ptitSeb** [comment]
The Witcher 2 !! Ah yeah, that would be an impressive demo indeed.

Now, I have added all SDL missing symbol, and also tmpname. All other symbols are from openal, and they are all supported currently. So I guess it's not directly linked to openal, but somehow get it in some inderect way. In case it use alut, I have added openal as a dependancy, but I doubt it use it. Can you give me the full log (I need the list of loaded libs at the beggining).

**Comment by ITotalJustice** [comment]
Thanks! And yes it would be amazing to see it running.  [Here's the full log](https://ufile.io/oowd9apw)

Noticed it got further now with the sdl symbols added, now it ends with `10717|0x2012f7a6: Unimplemented Opcode 66 8C E2 66 85 D2 89 E5`

**Comment by ptitSeb** [comment]
So, I added the missing opcode. It was `mov dx, fs`, so I'm unsure what will happens next, because my emulation of the segments register is really the bare minimum...

About the openal symbol, I don't see anything wrong for now. I need to grab my copy of witcher 2 and analyse `libopenal-eon.so.1`, but I first need to download the massive 20Go install... so not for today!

**Comment by ITotalJustice** [comment]
Thanks again! Yeah the error is now  `ERROR - eON failed to initialise!`And nice that you have the game, will be much faster for you to debug :)

**Comment by ptitSeb** [comment]
Yeah, I'll try to debug it tomorrow or maybe next week (as I still need to download it first)

**Comment by Jack-Rickwood** [comment]
Any news on this? It would be so cool if witcher 2 ran on this!

**Comment by ptitSeb** [comment]
No yet, I'm still working on global stabilisation. I haven't started looking at this one yet.

**Comment by voltagex** [comment]
```
#0  0x20477000 in ?? ()
#1  0x0383cd24 in AllocElfMemory (context=0x3b32a30, head=0x0, head@entry=0x3b2d618, mainbin=62073376, mainbin@entry=1) at /home/pi/box86/src/elfs/elfloader.c:195
#2  0x0380ccdc in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /home/pi/box86/src/main.c:669

```

```
Adding "./witcher2" as #0 in elf collection
Elf Addr(v/p)=0x10000/0x10000 Memsize=0x20466e50 (align=0x1000)
Elf Stack Memsize=1048576 (align=4)
Elf TLS Memsize=0 (align=0)
Allocating 0x20467000 memory @0x10000 for Elf "./witcher2"
Segmentation fault
```

**Comment by ptitSeb** [comment]
Yes, so box86 was "in the way" of the witcher 2... I moved it away, but now, the witcher 2 beeing a Windows game with a custom wrapper, the code use FS: for the TLS data (like Wine). So, it still doesn't go very far for now.

**Comment by ptitSeb** [comment]
Witcher 2 for Linux works now on my side, but it needs an OpenGL 3.3 to really works. It doesn't seems to work fine on OpenGL 2.1.
