### ISSUE TITLE
Assetto Corsa Server

### ISSUE THREAD

**Issue by Kroustalo** [ptitSeb/box86#520]
Good afternoon, I'm experimenting with an Assetto Corsa Server running on my RPI4 running ubuntu server _Ubuntu 20.04.3 LTS aarch64_  but turns out that the linux excecutable is x86 (tested with a vm). I installed box64 and box86 and I came up with this...

```
box64 acServer
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.7 40c5824 built on Dec 11 2021 23:16:22
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 26 Env var
Looking for acServer
This is a 32bits ELF! box64 can only run 64bits ELF (/home/user/acs/64/acServer)!
Error: reading elf header of /home/user/acs/64/acServer, try to launch using box86 instead
Box86 with Dynarec v0.2.5 a1aac43a built on Dec 12 2021 12:20:51
```

So here we are... I'm not sure if it is actually running or is it bugged due to the program or the emilator but anyways, I decided to give it a shot here...

I'm attaching the excecutable's for debuging since it is standalone and does not require steam or the game itself to run
[assetto server test.zip](https://github.com/ptitSeb/box86/files/7699151/assetto.server.test.zip) (It's the default server config)

Thanks in advance!

**Comment by Hacker1245** [comment]
did you try running it with box86 iinstead of box64?

**Comment by Kroustalo** [comment]
Box86 runs the last line of the posted output. box64 does it automatically since both are installed.

**Comment by Hacker1245** [comment]
what if you try to run it with box86 manually?

**Comment by Kroustalo** [comment]
```
Kroustalo@Issue:~$ ./acServer
Box86 with Dynarec v0.2.5 a1aac43a built on Dec 12 2021 12:20:51
Kroustalo@Issue:~$ 
```
```
Kroustalo@Issue:~$ box86 acServer
Box86 with Dynarec v0.2.5 a1aac43a built on Dec 12 2021 12:20:51
Kroustalo@Issue:~$
```
Nothing afterwards. Ι also attached the **files** to do your own testing...

**Comment by Kroustalo** [comment]
Okay, I did some research and I found out that the server is only [32-bit](https://linuxgsm.com/servers/acserver/) (ignore the "64 bit" version)

I tried to run the debugger and I came up with this
```
BOX86_LOG=1 box86 ./acServer
Debug level is 1
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Box86 with Dynarec v0.2.5 a1aac43a built on Dec 12 2021 12:20:51
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 26 Env var
Looking for ./acServer
8021|SIGSEGV @0x628fe800 (???(box86/0x628fe800)) (x86pc=0xf77f4d2a/???:"???", esp=0xf6d8457c, stack=0xf6585000:0xf6d85000 own=(nil) fp=(nil)), for accessing 0x8 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0)
8021|Double SIGSEGV (code=1, pc=0x628fe800, addr=0x8)!
```

This is where I am now...

**Comment by ptitSeb** [comment]
Does this server runs now, with latest box86?
Can this ticket be closed?

**Comment by Kroustalo** [comment]
Haven't checked this since. Give me a couple of days to set it up again because I don't have access to my pi right now. I'll update soon.

**Comment by Kroustalo** [comment]
I tried to do a fresh install of box86 on Ubuntu 22.04 but it still not running...
```
$ lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
But this time I got a different responce...
```
$ ./acServer
Box86 with Dynarec v0.2.7 b8ec0f91 built on Oct 19 2022 13:25:00
fatal error: rt_sigaction read failure

runtime stack:
runtime.throw(0x82bc855, 0x19)
        c:/go/src/runtime/panic.go:596 +0x7c
runtime.getsig(0x40, 0x807dcc0)
        c:/go/src/runtime/os_linux.go:427 +0x5c
runtime.initsig(0x83e3900)
        c:/go/src/runtime/signal_unix.go:79 +0x70
runtime.mstart1()
        c:/go/src/runtime/proc.go:1175 +0x8e
runtime.mstart()
        c:/go/src/runtime/proc.go:1149 +0x4d

goroutine 1 [runnable]:
runtime.main()
        c:/go/src/runtime/proc.go:106
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1629 +0x1
```

**Comment by ptitSeb** [comment]
Ah, go runtime. I have to study this, there are a few tickets of go stuff not working properly.
