### ISSUE TITLE
Cannot install x86 32bit filebeat. 

### ISSUE THREAD

**Issue by kgoode517** [ptitSeb/box86#666]
Okay folks tried everything I could think of  was following this for a raspberry pi2 https://pimylifeup.com/raspberry-pi-x86/ got it installed fine was following the linux guide to get filebeat https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html with the 32 bit linux_x86
pi@raspberrypi:~/filebeat-7.17.4-linux-x86 $ sudo ./filebeat -e 
[sudo] password for pi: 
Box86 with Dynarec v0.2.7 e9fcef3d built on Aug 19 2022 23:30:42
It takes a whole five seconds before it returns that and gives me back my command prompt. Is there a log I can reference somewhere to try to figure out what is going on with box86? 
If I try running it a few times I can eventually have it give me the following error but have no idea what I am looking at. 
'''
Box86 with Dynarec v0.2.7 e9fcef3d built on Aug 19 2022 23:30:42
signal 23 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime: unexpected return pc for runtime.sigtramp called from 0x63f94030
stack: frame={sp:0x4246a968, fp:0x4246a988} stack=[0x42462908,0x4246ad08)
0x4246a8e8:  0x4246a8ec  0x71151370 <runtime.throw.func1+0x00000000>  0x734aa2ed  0x00000039 
0x4246a8f8:  0x7116a7a5 <runtime.sigNotOnStack+0x00000085>  0x734aa2ed  0x00000039  0x71169918 <runtime.adjustSignalStack+0x00000208> 
0x4246a908:  0x00000017  0x4246a920  0x4246a930  0x00000004 
0x4246a918:  0x00000008  0x00000000  0x42402000  0x00000001 
0x4246a928:  0x00008000  0x71169654 <runtime.sigtrampgo+0x000000f4>  0x00000017  0x75d11a80 
0x4246a938:  0x4246a944  0x00000000  0x711239dd <runtime.newobject+0x0000002d>  0x00000000 
0x4246a948:  0x00000000  0x00000000  0x00000000  0x00000000 
0x4246a958:  0x424001e0  0x42409c88  0x4246a994  0x71188e2f <runtime.sigtramp+0x0000002f> 
0x4246a968: <0x00000017  0x42409c88  0x4246a994  0x00000000 
0x4246a978:  0x00000000  0x00000000  0x00000002 !0x63f94030 
0x4246a988: >0x00000017  0x42409c88  0x4246a994  0x00000000 
0x4246a998:  0x00000000  0x71010101  0x10411318  0x00000001 
0x4246a9a8:  0x00000033  0x00000000  0x0000007b  0x0000007b 
0x4246a9b8:  0x00000000  0x00000000  0x00000000  0x4246acd4 
0x4246a9c8:  0x00000002  0x00000000  0x00000003  0x00020002 
0x4246a9d8:  0x00000000  0x00000000  0x7119e651 <syscall.Syscall+0x00000021>  0x00000073 
0x4246a9e8:  0x00000246  0x00000000  0x0000007b  0x4246aa14 
0x4246a9f8:  0x00000023  0x00000023  0x7116ec22 <runtime.concatstrings+0x000001b2>  0x4261800d 
runtime.throw({0x734aa2ed, 0x39})
	/usr/local/go/src/runtime/panic.go:1198 +0x70
runtime.sigNotOnStack(0x17)
	/usr/local/go/src/runtime/signal_unix.go:919 +0x85
runtime.adjustSignalStack(0x17, 0x75d11a80, 0x4246a944)
	/usr/local/go/src/runtime/signal_unix.go:510 +0x208
runtime.sigtrampgo(0x17, 0x42409c88, 0x4246a994)
	/usr/local/go/src/runtime/signal_unix.go:450 +0xf4
runtime: unexpected return pc for runtime.sigtramp called from 0x63f94030
stack: frame={sp:0x4246a968, fp:0x4246a988} stack=[0x42462908,0x4246ad08)
0x4246a8e8:  0x4246a8ec  0x71151370 <runtime.throw.func1+0x00000000>  0x734aa2ed  0x00000039 
0x4246a8f8:  0x7116a7a5 <runtime.sigNotOnStack+0x00000085>  0x734aa2ed  0x00000039  0x71169918 <runtime.adjustSignalStack+0x00000208> 
0x4246a908:  0x00000017  0x4246a920  0x4246a930  0x00000004 
0x4246a918:  0x00000008  0x00000000  0x42402000  0x00000001 
0x4246a928:  0x00008000  0x71169654 <runtime.sigtrampgo+0x000000f4>  0x00000017  0x75d11a80 
0x4246a938:  0x4246a944  0x00000000  0x711239dd <runtime.newobject+0x0000002d>  0x00000000 
0x4246a948:  0x00000000  0x00000000  0x00000000  0x00000000 
0x4246a958:  0x424001e0  0x42409c88  0x4246a994  0x71188e2f <runtime.sigtramp+0x0000002f> 
0x4246a968: <0x00000017  0x42409c88  0x4246a994  0x00000000 
0x4246a978:  0x00000000  0x00000000  0x00000002 !0x63f94030 
0x4246a988: >0x00000017  0x42409c88  0x4246a994  0x00000000 
0x4246a998:  0x00000000  0x71010101  0x10411318  0x00000001 
0x4246a9a8:  0x00000033  0x00000000  0x0000007b  0x0000007b 
0x4246a9b8:  0x00000000  0x00000000  0x00000000  0x4246acd4 
0x4246a9c8:  0x00000002  0x00000000  0x00000003  0x00020002 
0x4246a9d8:  0x00000000  0x00000000  0x7119e651 <syscall.Syscall+0x00000021>  0x00000073 
0x4246a9e8:  0x00000246  0x00000000  0x0000007b  0x4246aa14 
0x4246a9f8:  0x00000023  0x00000023  0x7116ec22 <runtime.concatstrings+0x000001b2>  0x4261800d 
runtime.sigtramp()
	/usr/local/go/src/runtime/sys_linux_386.s:431 +0x2f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1319 +0x1 fp=0x4246eff4 sp=0x4246eff0 pc=0x71187d31

goroutine 1 [running, locked to thread]:
	goroutine running on other thread; stack unavailable
'''

**Comment by kgoode517** [comment]
Self solved by using https://github.com/vrince/arm-beats instead.
